teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /merlin/mobile_base_controller/cmd_vel
    deadman_buttons: [0]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
        offset: 0.0
      -
        axis: 0
        target: angular.z
        scale: -0.5
        offset: 0.0
